//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tournament_421_Marushkina_Anastasia.Bases
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatchTeam
    {
        public int MatchTimeId { get; set; }
        public int MatchId { get; set; }
        public System.DateTime Timestamp { get; set; }
        public Nullable<int> Rang { get; set; }
        public Nullable<int> TeamID { get; set; }
    
        public virtual Match Match { get; set; }
        public virtual Teams Teams { get; set; }
    }
}
