//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tournament_421_Marushkina_Anastasia.Bases
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TournamentDB_421_Marushkina_AnastasiaEntities : DbContext
    {
        public TournamentDB_421_Marushkina_AnastasiaEntities()
            : base("name=TournamentDB_421_Marushkina_AnastasiaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Applications> Applications { get; set; }
        public virtual DbSet<Format> Format { get; set; }
        public virtual DbSet<Games> Games { get; set; }
        public virtual DbSet<Match> Match { get; set; }
        public virtual DbSet<MatchPlayer> MatchPlayer { get; set; }
        public virtual DbSet<MatchTeam> MatchTeam { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Statistics> Statistics { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TeamRole> TeamRole { get; set; }
        public virtual DbSet<Teams> Teams { get; set; }
        public virtual DbSet<Tournament> Tournament { get; set; }
        public virtual DbSet<Type> Type { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
