//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tournament_421_Marushkina_Anastasia.Bases
{
    using System;
    using System.Collections.Generic;
    
    public partial class Statistics
    {
        public int ID { get; set; }
        public Nullable<int> Kolvo_Match { get; set; }
        public Nullable<int> Winner { get; set; }
        public Nullable<int> Overs { get; set; }
        public Nullable<int> TourID { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public virtual Tournament Tournament { get; set; }
        public virtual Users Users { get; set; }
    }
}
